export const defaultChartConfig = {
  title: 'Escape artists',
  subtitle: 'Number of laboratory-acquired infections, 1970-2021',
  source: 'Sources: Laboratory-Acquired Infection Database; American Biological Safety Association',
  publisher: 'The Economist',
  width: 720,
  marginTop: 24,
  marginRight: 24,
  marginLeft: 136,
  barHeight: 30,
  barPadding: 0.4,
  xMax: 55,
  tickStep: 5,
  labelOutsideCount: 3,
  labelOffset: 8,
  axisExtension: 6,
  gridLabelOffset: -8,
  topRuleValue: 52.5,
  redRuleWidth: 34,
  redRuleHeight: 8,
  redRuleGap: 8,
  titleFontSize: 26,
  subtitleFontSize: 19,
  sourceFontSize: 14,
  labelFontSize: 13,
  gridLabelFontSize: 11,
  barColor: '#0a6ea2',
  outsideLabelColor: '#075f8d',
  insideLabelColor: '#ffffff',
  sourceColor: '#7f7f7f',
  gridColor: '#d8d8d8',
  gridLabelColor: '#9a9a9a',
  axisColor: '#777777',
  redColor: '#e3120b',
}
